### PR TITLE
Add error handling libraries & tests for GPU version

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Note that this won't pass testing on Travis because it doesn't have GPUs.  The code added looks like this:
```cpp
  // Paranoid code
  if (std::isnan(sqrt) || std::isinf(sqrt)) {
    // The condition above should be very, very infrequent.
    // Therefore capture/recalculate this intermediate value only when necessary.
    t<0>(sum_t).device(*dev.edevice) = t<1>(scratch_t).sum();
    float sum = gradient_norm_scratch[pi];

    cerr << "sqrt=" << sqrt << ", sum=" << sum;
    for (size_t i = 0; i < all_params.size(); ++i) {
      float value = gradient_norm_scratch[i];
      if (std::isnan(value) || std::isinf(value) || value < 0)
        cerr << ", " << i << "=" << value;
    }
    cerr << endl;

    if (!std::isnan(sum) && !std::isinf(sum) && sum < 0)
      return 0; // Try to do something about it.
  }
```
It assumes that the error condition is very infrequent and goes ahead and recalculates the sum and prints the sqrt, sum, and any of the elements being summed that are inf, nan, or < 0 for debugging.  If the sqrt of a negative value was taken, the square root is set to zero so that the calling function will not throw an exception about it.

The values calculated by the GPU can and do differ from values from the CPU.  Each is consistent, so far, across operating systems, and a test was added to make sure it stays that way.

**Comment by kwalcock** [comment]
After this is merged, the GPU version should be built from the cuda branch and no longer the cudaErrorHandling one.

**Comment by kwalcock** [comment]
If there is code from flair that can be used to handle error conditions, it might be nice to add it to a utility function in this project for reference.

**Comment by MihaiSurdeanu** [comment]
Thanks!

Can you please add an apply() method to the SafeTrainer class? So we don't have to type the "new " in front of SafeTrainer? :)

**Comment by kwalcock** [comment]
If I remember correctly, this will come for free in Scala 3.  No more new is required.  I jumped the gun.

**Pull request merged**
